### using the token of a logged in User which has the Custom Claim role not set. Save it here.
@Token = 

### delete using valid id for entry that exists
DELETE http://localhost:8103/entry/5
Authorization: Bearer {{Token}}

### delete using invalid datatype for id | SHOULD FAIL & RETURN 400
DELETE http://localhost:8103/entry/stkra
Authorization: Bearer {{Token}}

### delete using valid id for entry that doesnt exist | SHOULD FAIL & RETURN 404
DELETE http://localhost:8103/entry/476
Authorization: Bearer {{Token}}