### ----- GET BY ID: localhost:8103/entry/:id -----

### providing valid id of type number for entry that exists (check database)
GET http://localhost:8103/entry/1

### providing valid id of type number for entry that DOES NOT exist | SHOULD FAIL & RETURN 404
GET http://localhost:8103/entry/12932

### providing invalid id (not in form of number) | SHOULD FAIL & RETURN 400
GET http://localhost:8103/entry/4gustav


### ----- GET ALL: localhost:8103/entry?verified={verified}&amount={amount}&page={page} -----

### using the token of a logged in User which has the Custom Claim role not set. Save it here.
@Token = 

### verified, amount and page set
GET http://localhost:8103/entry/?verified=false&amount=1&page=0
Authorization: Bearer {{Token}}

### amount and page set | verified undefined | SHOULD IGNORE VERIFIED STATUS
GET http://localhost:8103/entry?amount=5&page=0
Authorization: Bearer {{Token}}

### verified and amount set | page undefined | SHOULD TAKE FIRST PAGE (SAME AS PAGE=0)
GET http://localhost:8103/entry?verified=false&amount=3
Authorization: Bearer {{Token}}

### only amount set | SHOULD TAKE FIRST AMOUNT RESULTS, IGNORE VERIFIED STATUS
GET http://localhost:8103/entry?amount=7
Authorization: Bearer {{Token}}

### only verified set 
GET http://localhost:8103/entry?verified=false
Authorization: Bearer {{Token}}

### nothing set | SHOULD RETURN ALL ENTRIES
GET http://localhost:8103/entry
Authorization: Bearer {{Token}}

### wrong data type of verfiied | SHOULD RETURN 400 
GET http://localhost:8103/entry?verified=gustav
Authorization: Bearer {{Token}}