### Update seems to ignore wrong-written property names & correct properties that have
### the same data in them already stored -> stays the same

### using the token of a logged in User which has the Custom Claim role not set. Save it here.
@Token = 

### Update Adress & Lat Long on existing entry
PUT http://localhost:8103/entry/2
Authorization: Bearer {{Token}}
content-type: application/json

{
    "editedEntry": {
        "address": "Amrumer Straße 17, 13353 Berlin, Deutschland",
        "latitude": 52.2315,
        "longitude": 13.3,
        "verified": true
    }
}

### Add contact information on existing entry (was undefined before)
PUT http://localhost:8103/entry/8
Authorization: Bearer {{Token}}
content-type: application/json

{
    "editedEntry": {
        "telefon": "012839239",
        "website": "berlin-web.de",
        "description": "Deine krasse Webagentur in Berlin! Wir sind immer für dich da."
    }
}

### Test only setting verified
PUT http://localhost:8103/entry/8
Authorization: Bearer {{Token}}
content-type: application/json

{
    "editedEntry": {
        "verified": true
    }
}

### Try to edit using inproper datatype for id | SHOULD FAIL & RETURN 400
PUT http://localhost:8103/entry/oispws
Authorization: Bearer {{Token}}
content-type: application/json

{
    "editedEntry": {
        "telefon": "012839239",
        "website": "berlin-web.de",
        "description": "Deine Webagentur in Berlin! Wir sind immer für dich da."
    }
}

### Try to edit entry with unknown id | SHOULD FAIL & RETURN 404
PUT http://localhost:8103/entry/9203
Authorization: Bearer {{Token}}
content-type: application/json

{
    "editedEntry": {
        "telefon": "012839239",
        "website": "berlin-web.de",
        "description": "Deine Webagentur in Berlin! Wir sind immer für dich da."
    }
}

### Try to edit without providing request body | SHOULD FAIL & RETURN 400 -> returned 415 Unsupported Media Type - Sollte fine sein mMn
PUT http://localhost:8103/entry/1
Authorization: Bearer {{Token}}

### Try to edit unknown property | RETURNS 400 -> returned tatsächlich 200, ändert aber nichts, da es das Feld nicht gibt, ist das okay?
PUT http://localhost:8103/entry/1
Authorization: Bearer {{Token}}
content-type: application/json

{
    "editedEntry": {
        "telefon": "287729830",
        "shoesize": 38
    }
}

### Try to edit known property using inproper datatype | RETURNS 400 -> returned 500, Prisma gibt den Fehler, ist das okay?
PUT http://localhost:8103/entry/1
Authorization: Bearer {{Token}}
content-type: application/json

{
    "editedEntry": {
        "company": 13
    }
}



