services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: $DB_PWD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    ports:
      - "127.0.0.1:5432:5432"
  backend:
    build:
      context: ../../
      dockerfile: ./apps/backend/Dockerfile
    environment:
      HOST: 0.0.0.0
      DATABASE_URL: postgres://$DB_USER:$DB_PWD@db:5432/$DB_NAME
      PORT: 8101
    ports:
      - "127.0.0.1:8101:8101"
