services:
  db:
    image: postgis/postgis:14-3.2-alpine
    environment:
      POSTGRES_PASSWORD: $DB_PWD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    ports:
      - "127.0.0.1:5433:5432"
