/**
 * Generated by orval v6.5.1 🍺
 * Do not edit manually.
 * Venture Capitol API
 * Open API specification for the Venture Capitol API
 * OpenAPI spec version: 1.0.0
 */
export type MakeDecisionBody = {
	selectedPath?: number;
};

export type CreateCompanyBody = {
	legalForm?: string;
	name?: string;
};

export type CompanyLegalForm =
	| "EINZELUNTERNEHMER"
	| "GBR"
	| "FREIBERUFLER"
	| "PARTG"
	| "UG"
	| "GMBH";

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CompanyLegalForm = {
	EINZELUNTERNEHMER: "EINZELUNTERNEHMER" as CompanyLegalForm,
	GBR: "GBR" as CompanyLegalForm,
	FREIBERUFLER: "FREIBERUFLER" as CompanyLegalForm,
	PARTG: "PARTG" as CompanyLegalForm,
	UG: "UG" as CompanyLegalForm,
	GMBH: "GMBH" as CompanyLegalForm,
};

export interface Company {
	id?: string;
	name?: string;
	users?: string[];
	legalForm?: CompanyLegalForm;
}

export interface MadeDecision {
	decisionId: string;
	selectedPath: number;
}

export interface CompletedTask {
	taskId: string;
}

export interface User {
	id: string;
	companies: Company[];
}
