openapi: 3.0.1
info:
  title: Venture Capitol API
  description: Open API specification for the Venture Capitol API
  version: 1.0.0
servers:
  - url: http://localhost:8101/api
  - url: https://localhost:8101/api
tags:
  - name: company
    description: API for company information
  - name: user
    description: API for user information
  - name: task
    description: API for decision information
  - name: decision
    description: API for task information
paths:
  /user/{userId}:
    get:
      tags:
        - user
      summary: Get a user by id
      description: Returns a user with given id
      operationId: getUserById
      security:
        - firebaseAuth: []
      parameters:
        - name: userId
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Invalid parameters.
        404:
          description: User not found.
  /company:
    post:
      tags:
        - company
      summary: Adds a new company to Venture Capitol
      description: Posts a company with given data
      operationId: createCompany
      security:
        - firebaseAuth: []
      requestBody:
        description: company which will be founded
        content:
          application/json:
            schema:
              type: object
              properties:
                legalForm:
                  type: string
                name:
                  type: string
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
        400:
          description: Invalid parameters.
      x-codegen-request-body-name: company
  /company/{companyId}:
    get:
      tags:
        - company
      summary: Get a company by id
      description: Returns a company with given id
      security:
        - firebaseAuth: []
      parameters:
        - name: companyId
          in: path
          description: ID of the company
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Company"
    delete:
      tags:
        - company
      summary: Delete a company by id
      description: Deletes a company with given id
      operationId: deleteCompany
      security:
        - firebaseAuth: []
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation.
  /company/{companyId}/tasks:
    get:
      tags:
        - task
      summary: Get all tasks of a company
      description: Returns which tasks of a company are done
      operationId: getDoneTasks
      security:
        - firebaseAuth: []
      parameters:
        - name: companyId
          in: path
          description: ID of the company
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompletedTask"
        400:
          description: Invalid status value
  /company/{companyId}/tasks/{taskId}:
    post:
      tags:
        - task
      summary: Add a checked task to a company
      description: Adds a new finished task to a company
      security:
        - firebaseAuth: []
      operationId: markTaskDone
      parameters:
        - name: companyId
          in: path
          description: ID of the company
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          description: ID of the task
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation.
        400:
          description: Invalid parameters.
        404:
          description: Company not found.
    delete:
      tags:
        - task
      summary: Delete a task from a company
      description: Deletes a task from a company
      operationId: undoTaskCompletion
      security:
        - firebaseAuth: []
      parameters:
        - name: companyId
          in: path
          description: ID of the company
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          description: ID of the task
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful deletion.
  /company/{companyId}/decisions:
    get:
      tags:
        - decision
      summary: Get all decisions of a company
      description: Returns all decisions of a company
      security:
        - firebaseAuth: []
      operationId: getMadeDecisions
      parameters:
        - name: companyId
          in: path
          description: ID of the company
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MadeDecision"
  /company/{companyId}/decisions/{decisionId}:
    post:
      tags:
        - decision
      summary: Add a decision to a company
      description: Adds a new decision to a company
      operationId: makeDecision
      security:
        - firebaseAuth: []
      parameters:
        - name: companyId
          in: path
          description: ID of the company
          required: true
          schema:
            type: string
        - name: decisionId
          in: path
          description: ID of the decision
          required: true
          schema:
            type: string
      requestBody:
        description: Selected path of the decision
        content:
          application/json:
            schema:
              type: object
              properties:
                selectedPath:
                  type: integer
        required: true
      responses:
        200:
          description: successful operation
    delete:
      tags:
        - decision
      summary: Delete a decision from a company
      description: Deletes a decision from a company
      operationId: undoDecision
      security:
        - firebaseAuth: []
      parameters:
        - name: companyId
          in: path
          description: ID of the company
          required: true
          schema:
            type: string
        - name: decisionId
          in: path
          description: ID of the decision
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful deletion
components:
  securitySchemes:
    firebaseAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      required:
        - companies
        - id
      type: object
      properties:
        id:
          type: string
        companies:
          type: array
          items:
            $ref: "#/components/schemas/Company"
    CompletedTask:
      required:
        - companyId
        - taskId
      type: object
      properties:
        taskId:
          type: string
    MadeDecision:
      required:
        - companyId
        - decisionId
        - selectedPath
      type: object
      properties:
        decisionId:
          type: string
        selectedPath:
          type: integer
    Company:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        users:
          type: array
          items:
            type: string
            example: "aijd10-ihgjgfjd-aimlhmpbtm"
        legalForm:
          type: string
          enum:
            - EINZELUNTERNEHMER
            - GBR
            - FREIBERUFLER
            - PARTG
            - UG
            - GMBH
        # completedTask:
        #   type: array
        #   items:
        #     $ref: "#/components/schemas/CompletedTask"
        # madeDecision:
        #   type: array
        #   items:
        #     $ref: "#/components/schemas/MadeDecision"
