### --- GET /company/:companyId --- ###

### providing valid id of type number for entry that exists (check database)
GET http://localhost:8101/api/company/1

### providing invalid id (not in form of number) | SHOULD FAIL & RETURN 400
GET http://localhost:8101/api/entry/99A

### providing valid id of type number for entry that DOES NOT exist | SHOULD FAIL & RETURN 404
GET http://localhost:8101/api/entry/99


### --- GET /company/:companyId/decisions --- ###

### providing valid id of type number for entry that exists (check database)
GET http://localhost:8101/api/company/1/decisions

### providing invalid id (not in form of number) | SHOULD FAIL & RETURN 400
GET http://localhost:8101/api/company/99A/decisions

### providing valid id of type number for entry that DOES NOT exist | SHOULD FAIL & RETURN 404
GET http://localhost:8101/api/company/99/decisions


### --- GET /company/:companyId/tasks --- ###

### providing valid id of type number for entry that exists (check database)
GET http://localhost:8101/api/company/1/tasks

### providing invalid id (not in form of number) | SHOULD FAIL & RETURN 400
GET http://localhost:8101/api/company/99A/tasks

### providing valid id of type number for entry that DOES NOT exist | SHOULD FAIL & RETURN 404
GET http://localhost:8101/api/company/99/tasks


### --- GET /user/:userId --- ###

### providing valid id of type number for entry that exists (check database)
GET http://localhost:8101/api/user/1

### providing invalid id (not in form of number) | SHOULD FAIL & RETURN 400
GET http://localhost:8101/api/user/99A

### providing valid id of type number for entry that DOES NOT exist | SHOULD FAIL & RETURN 404
GET http://localhost:8101/api/user/99
