name: Backend CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: backend
  PROJECT_ID: venture-capitol
  REPO_ID: images
  GAR_HOSTNAME: europe-west1-docker.pkg.dev

jobs:
  # ------------------------------------------ DOCKER BUILD ------------------------------------------
  build-push-gcr:
    name: "Docker: Build and Push Container"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Files
        uses: actions/checkout@v2

      # This sets the GOOGLE_APPLICATION_CREDENTIALS environment variable
      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: ${{ secrets.DEPLOY_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker $GAR_HOSTNAME --quiet

      - name: Pull previous container file to use as cache
        continue-on-error: true
        run: docker pull $GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:latest

      - name: Build the Docker Image
        run: |-
          docker build \
          --cache-from=$GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:latest \
          -t $GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:latest \
          -t $GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:${GITHUB_SHA::6} \
          -f ./apps/backend/Dockerfile .

      - name: Push the Docker Image to Google Artifact Registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |-
          docker push $GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:latest
          docker push $GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:${GITHUB_SHA::6}

  # ------------------------------------------ VALIDATE TF ------------------------------------------
  validate-tf:
    name: "Validate Terraform Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Files
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: ${{ secrets.DEPLOY_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Export image names as environment variables
        id: step_one
        run: |
          echo "TF_VAR_staging_image_name=$GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:${GITHUB_SHA::6}" >> $GITHUB_ENV
          echo "TF_VAR_image_name=$GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:${GITHUB_SHA::6}" >> $GITHUB_ENV

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        id: fmt
        working-directory: ./deploy
        run: terraform fmt -check

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        id: init
        working-directory: ./deploy
        run: terraform init

      # Terraform validate
      - name: Terraform Validate
        id: validate
        working-directory: ./deploy
        run: terraform validate -no-color

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        working-directory: ./deploy
        run: terraform plan -no-color

      # Show terraform plan as comment in PR
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  # ------------------------------------------ STAGING ------------------------------------------
  deploy-staging:
    name: "Deploy to Staging"
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://staging.venturecapitol.de
    needs: [build-push-gcr, validate-tf]
    outputs:
      currentRevision: ${{ steps.get-current-revision.outputs.json }}
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout Repository Files
        uses: actions/checkout@v2

      - name: Get the current revision description
        id: get-current-revision
        run: |
          content=`gcloud run services describe vc-backend --region europe-west1 --format=json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=json::$content"

      - name: Export image names as environment variables
        run: |
          echo "TF_VAR_staging_image_name=$GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:${GITHUB_SHA::6}" >> $GITHUB_ENV
          echo "TF_VAR_image_name=${{fromJson(steps.get-current-revision.outputs.json).spec.template.spec.containers[0].image}}" >> $GITHUB_ENV

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: ${{ secrets.DEPLOY_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Terraform Init
        id: init
        working-directory: ./deploy
        run: terraform init

      # On push to master, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        working-directory: ./deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

  # ------------------------------------------ PROD ------------------------------------------
  deploy-prodction:
    name: "Deploy to Production"
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://venturecapitol.de
    needs: [deploy-staging]

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout Repository Files
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.3
        with:
          credentials_json: ${{ secrets.DEPLOY_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Export image names as environment variables
        run: |
          echo "TF_VAR_staging_image_name=$GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:${GITHUB_SHA::6}" >> $GITHUB_ENV
          echo "TF_VAR_image_name=$GAR_HOSTNAME/$PROJECT_ID/$REPO_ID/$IMAGE_NAME:${GITHUB_SHA::6}" >> $GITHUB_ENV

      - name: Terraform Init
        id: init
        working-directory: ./deploy
        run: terraform init

      # On push to master, build or change infrastructure according to Terraform configuration files
      - name: Terraform Apply
        working-directory: ./deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
