name: Frontend Cypress Test
on:
  push:
    paths:
      - "apps/frontend/**"
      - .github/workflows/cypress-frontend.yaml
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          start: lerna bootstrap
      - name: Run Component Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          project: apps/frontend
          command: npm run cypress:run-ct
      - name: Run Integration Tests
        uses: cypress-io/github-action@v2
        with:
          install: false
          project: apps/frontend
          start: npm start
