name: Frontend Cypress Test
on:
  push:
    paths:
      - "apps/frontend/**"
      - .github/workflows/cypress-frontend.yaml
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci
      - run: lerna bootstrap
      - run: npm run cypress:run-ct
      - run: npm run cypress:run

